/**
 * Définition de tous les blocs Blockly organisés par catégorie.
 * Basé sur les fichiers toolbox_*.json et ai-blocks.js.
 */
export const BLOCKS_BY_CATEGORY: Record<string, { name: string; blocks: string[] }> = {
  LOGIC: {
    name: 'Logique',
    blocks: [
      'controls_if',
      'logic_compare',
      'logic_operation',
      'logic_negate',
      'logic_boolean',
      'logic_null',
      'logic_ternary',
      'controls_switch',
    ],
  },
  LOOPS: {
    name: 'Boucles',
    blocks: [
      'controls_repeat_ext',
      'controls_repeat',
      'controls_whileUntil',
      'controls_for',
      'controls_forEach',
      'controls_flow_statements',
    ],
  },
  MATH: {
    name: 'Math',
    blocks: [
      'math_number',
      'math_arithmetic',
      'math_single',
      'math_trig',
      'math_constant',
      'math_number_property',
      'math_round',
      'math_on_list',
      'math_modulo',
      'math_constrain',
      'math_random_int',
    ],
  },
  TEXT: {
    name: 'Texte',
    blocks: [
      'text',
      'text_join',
      'text_append',
      'text_length',
      'text_isEmpty',
      'text_indexOf',
      'text_charAt',
      'text_getSubstring',
      'text_changeCase',
      'text_trim',
      'text_count',
      'text_replace',
      'text_print',
      'text_prompt_ext',
    ],
  },
  LIST: {
    name: 'Listes',
    blocks: [
      'lists_create_with',
      'lists_repeat',
      'lists_length',
      'lists_isEmpty',
      'lists_indexOf',
      'lists_getIndex',
      'lists_setIndex',
      'lists_getSublist',
      'lists_split',
      'lists_sort',
      'lists_reverse',
    ],
  },
  COLOUR: {
    name: 'Couleur',
    blocks: [
      'colour_picker',
      'colour_random',
      'colour_rgb',
      'colour_blend',
    ],
  },
  VARIABLES: {
    name: 'Variables',
    blocks: [],
  },
  FUNCTIONS: {
    name: 'Fonctions',
    blocks: [],
  },
  BOARD: {
    name: 'Carte',
    blocks: [
      'board_base_inout_buildin_led',
      'board_base_inout_digital_write',
      'board_base_inout_digital_read',
      'board_base_inout_highlow',
      'board_base_inout_analog_write',
      'board_base_inout_analog_read',
      'board_base_delay',
      'board_base_angle',
      'board_base_map',
      'board_base_inout_tone',
      'board_base_inout_notone',
      'board_serial_init',
      'board_serial_printfor',
      'board_serial_print',
      'board_serial_available',
      'board_serial_read',
      'board_serial_readStringUntil',
      'board_serial_flush',
    ],
  },
  SEEED: {
    name: 'Grove',
    blocks: [
      'grove_led',
      'grove_button',
      'grove_relay',
      'grove_tilt_switch',
      'grove_piezo_buzzer',
      'grove_pir_motion_sensor',
      'grove_line_finder',
      'grove_rgb_led',
      'grove_ultrasonic_ranger',
      'grove_rotary_angle',
      'grove_temperature_sensor',
      'grove_sound_sensor',
      'grove_thumb_joystick',
      'grove_serial_lcd_print',
      'grove_serial_lcd_power',
      'grove_serial_lcd_effect',
      'grove_motor_shield',
    ],
  },
  DS18B20: {
    name: 'DS18B20',
    blocks: [
      'ds18b20_search',
      'ds18b20_temp',
    ],
  },
  RELAY: {
    name: 'Relais',
    blocks: [
      'RELAY_LOGICAL',
      'RELAY_MOSFET',
    ],
  },
  SERVO: {
    name: 'Servo',
    blocks: [
      'servo_move',
      'servo_read_degrees',
    ],
  },
  AI: {
    name: 'IA Camera',
    blocks: [
      'ai_camera_open',
      'ai_detect',
      'ai_follow_line',
      'ai_sprite_say',
      'ai_sprite_move',
      'ai_sprite_turn',
      'ai_wait',
      'ai_camera_close',
    ],
  },
  ROBOT: {
    name: 'Robot',
    blocks: [
      'robot_forward',
      'robot_backward',
      'robot_turn_left',
      'robot_turn_right',
      'robot_set_speed',
      'robot_stop',
      'robot_gripper_open',
      'robot_gripper_close',
      'robot_gripper_stop',
    ],
  },
  PHONE: {
    name: 'Capteurs téléphone',
    blocks: [
      'phone_connect',
      'phone_activate',
      'phone_read_accelerometer',
      'phone_read_gyroscope',
      'phone_read_gps',
      'phone_read_microphone',
      'phone_use_camera',
      'phone_camera_window_open',
      'phone_vision_start',
      'phone_use_local_camera',
      'phone_drive_tilt',
      'phone_stop_on_noise',
      'phone_udp_start',
      'phone_udp_stop',
    ],
  },
};

/** Dictionnaire de traduction des types de blocs en français */
const BLOCK_LABELS_FR: Record<string, string> = {
  // Logique
  controls_if: 'Si / Sinon',
  logic_compare: 'Comparateur',
  logic_operation: 'Opérateur logique',
  logic_negate: 'Négation',
  logic_boolean: 'Booléen',
  logic_null: 'Nul',
  logic_ternary: 'Ternaire',
  controls_switch: 'Switch',
  // Boucles
  controls_repeat_ext: 'Répéter',
  controls_repeat: 'Répéter N fois',
  controls_whileUntil: 'Tant que / Jusqu\'à',
  controls_for: 'Pour',
  controls_forEach: 'Pour chaque',
  controls_flow_statements: 'Contrôle de flux',
  // Math
  math_number: 'Nombre',
  math_arithmetic: 'Arithmétique',
  math_single: 'Opération simple',
  math_trig: 'Trigonométrie',
  math_constant: 'Constante',
  math_number_property: 'Propriété nombre',
  math_round: 'Arrondi',
  math_on_list: 'Math sur liste',
  math_modulo: 'Modulo',
  math_constrain: 'Contraindre',
  math_random_int: 'Aléatoire entier',
  // Texte
  text: 'Texte',
  text_join: 'Concaténer',
  text_append: 'Ajouter',
  text_length: 'Longueur',
  text_isEmpty: 'Est vide',
  text_indexOf: 'Index de',
  text_charAt: 'Caractère à',
  text_getSubstring: 'Sous-chaîne',
  text_changeCase: 'Changer casse',
  text_trim: 'Nettoyer',
  text_count: 'Compter',
  text_replace: 'Remplacer',
  text_print: 'Afficher',
  text_prompt_ext: 'Demander',
  // Listes
  lists_create_with: 'Créer liste',
  lists_repeat: 'Répéter liste',
  lists_length: 'Longueur liste',
  lists_isEmpty: 'Liste vide',
  lists_indexOf: 'Index dans liste',
  lists_getIndex: 'Obtenir élément',
  lists_setIndex: 'Définir élément',
  lists_getSublist: 'Sous-liste',
  lists_split: 'Diviser / Joindre',
  lists_sort: 'Trier',
  lists_reverse: 'Inverser',
  // Couleur
  colour_picker: 'Palette',
  colour_random: 'Couleur aléatoire',
  colour_rgb: 'Couleur RGB',
  colour_blend: 'Mélanger',
  // Carte Arduino
  board_base_inout_buildin_led: 'LED intégrée',
  board_base_inout_digital_write: 'Écriture numérique',
  board_base_inout_digital_read: 'Lecture numérique',
  board_base_inout_highlow: 'Haut / Bas',
  board_base_inout_analog_write: 'Écriture analogique',
  board_base_inout_analog_read: 'Lecture analogique',
  board_base_delay: 'Pause',
  board_base_angle: 'Angle',
  board_base_map: 'Mapper',
  board_base_inout_tone: 'Son',
  board_base_inout_notone: 'Arrêter son',
  board_serial_init: 'Initialiser série',
  board_serial_printfor: 'Afficher format',
  board_serial_print: 'Afficher série',
  board_serial_available: 'Série disponible',
  board_serial_read: 'Lire série',
  board_serial_readStringUntil: 'Lire jusqu\'à',
  board_serial_flush: 'Vider série',
  // Grove
  grove_led: 'LED Grove',
  grove_button: 'Bouton',
  grove_relay: 'Relais',
  grove_tilt_switch: 'Inclinaison',
  grove_piezo_buzzer: 'Buzzer',
  grove_pir_motion_sensor: 'Mouvement PIR',
  grove_line_finder: 'Détecteur ligne',
  grove_rgb_led: 'LED RGB',
  grove_ultrasonic_ranger: 'Ultrason',
  grove_rotary_angle: 'Angle rotatif',
  grove_temperature_sensor: 'Température',
  grove_sound_sensor: 'Son',
  grove_thumb_joystick: 'Joystick',
  grove_serial_lcd_print: 'Afficher LCD',
  grove_serial_lcd_power: 'Power LCD',
  grove_serial_lcd_effect: 'Effet LCD',
  grove_motor_shield: 'Moteur',
  // DS18B20
  ds18b20_search: 'Chercher DS18B20',
  ds18b20_temp: 'Température DS18B20',
  // Relais
  RELAY_LOGICAL: 'Relais logique',
  RELAY_MOSFET: 'Relais MOSFET',
  // Servo
  servo_move: 'Déplacer servo',
  servo_read_degrees: 'Lire angle servo',
  // IA Camera
  ai_camera_open: 'Ouvrir caméra',
  ai_detect: 'Détecter',
  ai_follow_line: 'Suivre ligne',
  ai_sprite_say: 'Dire',
  ai_sprite_move: 'Déplacer sprite',
  ai_sprite_turn: 'Tourner sprite',
  ai_wait: 'Attendre',
  ai_camera_close: 'Fermer caméra',
  // Robot
  robot_forward: 'Avancer',
  robot_backward: 'Reculer',
  robot_turn_left: 'Tourner gauche',
  robot_turn_right: 'Tourner droite',
  robot_set_speed: 'Vitesse',
  robot_stop: 'Arrêter robot',
  robot_gripper_open: 'Ouvrir pince',
  robot_gripper_close: 'Fermer pince',
  robot_gripper_stop: 'Arrêter pince',
  // Téléphone
  phone_connect: 'Connecter téléphone',
  phone_activate: 'Activer capteurs',
  phone_read_accelerometer: 'Lire accéléromètre',
  phone_read_gyroscope: 'Lire gyroscope',
  phone_read_gps: 'Lire GPS',
  phone_read_microphone: 'Lire micro',
  phone_use_camera: 'Utiliser caméra téléphone',
  phone_camera_window_open: 'Fenêtre caméra',
  phone_vision_start: 'Préparer vision',
  phone_use_local_camera: 'Caméra locale',
  phone_drive_tilt: 'Piloter inclinaison',
  phone_stop_on_noise: 'Arrêter sur bruit',
  phone_udp_start: 'Démarrer temps réel',
  phone_udp_stop: 'Arrêter temps réel',
};

/** Transforme un type de bloc en libellé français lisible */
export function blockTypeToLabel(blockType: string): string {
  return BLOCK_LABELS_FR[blockType] ?? blockType
    .replace(/^(ai|robot|phone|board|grove|ds18b20|servo|relay)_/i, '')
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
