export {
  AI_SERVICE_DEFAULT_URL,
  ARDUINO_SERVICE_DEFAULT_URL,
  BLOCKLY_WORKSPACE_URL,
  BOARDS,
  DEFAULT_AI_PROJECT,
  DEFAULT_AI_SPRITE,
  DEFAULT_AI_USER,
  DEFAULT_CODE,
  DEFAULT_ROVER_3D,
  PHONE_SENSOR_SERVICE_DEFAULT_URL,
  SENSAGRAM_DEFAULT_HOST,
  boardById,
  createAiClient,
  createSensagramClient,
  createStorageAdapter,
  normalizeDetectionResult,
  resolveServiceUrl,
} from '@blocklyduino/shared';
export type {
  AiClient,
  AiDetectionKind,
  AiDetectionResult,
  AiInferenceRequest,
  AiProject,
  AiRuntimeEvent,
  AiSprite,
  AiUser,
  Board,
  CameraControlRequest,
  CameraControlResponse,
  CameraGestureCommand,
  CameraGestureEvent,
  CameraStatus,
  PortInfo,
  PhoneControlRequest,
  PhoneControlResponse,
  PhoneRuntimeEvent,
  PhoneSensorReading,
  PhoneSensorStatus,
  PhoneSensorsResponse,
  Rover3D,
  SparkiCommandResponse,
  StorageAdapter,
} from '@blocklyduino/shared';
